[package]
name = "tynding"
version = "0.2.0"
edition = "2021"
rust-version = "1.89"
publish = false

[lib]
crate-type = ["rlib", "staticlib"]
name = "tynding"

[[bin]]
name = "document"
path = "document.rs"

[dependencies]
extendr-api = {
  git = "https://github.com/extendr/extendr.git",
  rev = "baa377e073d19a3105d36533ab6c5f0c225bf420"
}
typst = "0.15.0"
typst-as-lib = { version = "0.15.5", features = ["typst-html"] }
typst-html = "0.15.0"
typst-kit = { version = "0.15.0", default-features = false }
typst-layout = "0.15.0"
typst-pdf = "0.15.0"
typst-render = "0.15.0"
typst-svg = "0.15.0"
typst-syntax = "0.15.0"

[profile.release]
lto = true
codegen-units = 1
