# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tynding_wrappers", use_symbols = TRUE, package_name = "tynding")

#' @usage NULL
#' @useDynLib tynding, .registration = TRUE
NULL

#' Compile a `.typ` file to a `.pdf` file and return the output path.
#' @param file Path to an existing `.typ` file.
#' @param output Optional output path. Defaults to the input path with `.pdf`.
#' @export
typst_compile <- function(file, output = NULL) .Call(wrap__typst_compile, file, output)


# nolint end
