# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_tynding_wrappers", use_symbols = TRUE, package_name = "tynding")

#' @usage NULL
#' @useDynLib tynding, .registration = TRUE
NULL

#' @title Compile a `.typ` file to a `.pdf` file and return the output path.
#'
#' @description This functions uses the Tyspt Rust library to compile a
#' `.typ` file to a `.pdf` file and return the output path.
#'
#' @param file Path to an existing `.typ` file.
#' @param output Optional output path. Defaults to the input path with `.pdf`.
#'
#' @return Output path, invisibly.
#'
#' @export
typst_compile <- function(file, output = NULL, font_path = NULL) .Call(wrap__typst_compile, file, output, font_path)


# nolint end
