on:
  push:
    branches: [main]
  pull_request:

name: R unit testing

permissions: read-all

jobs:
  test-units:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Windows GNU Rust target
        if: runner.os == 'Windows'
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-gnu

      - name: Install R dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::testthat, any::xml2, any::devtools

      - name: Run unit tests
        run: |
          devtools::load_all()
          testthat::test_dir("tests/testthat", stop_on_failure = TRUE)
        shell: Rscript {0}
